# Generated by Django 4.2.16 on 2026-04-17 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayByPlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_num', models.IntegerField()),
                ('period', models.IntegerField()),
                ('clock', models.CharField(max_length=10)),
                ('event_type', models.CharField(choices=[('field_goal_made', 'Field Goal Made'), ('field_goal_missed', 'Field Goal Missed'), ('free_throw', 'Free Throw'), ('rebound', 'Rebound'), ('turnover', 'Turnover'), ('foul', 'Foul'), ('substitution', 'Substitution'), ('timeout', 'Timeout'), ('jump_ball', 'Jump Ball'), ('violation', 'Violation'), ('period_start', 'Period Start'), ('period_end', 'Period End')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('loc_x', models.FloatField(blank=True, null=True)),
                ('loc_y', models.FloatField(blank=True, null=True)),
                ('shot_distance', models.FloatField(blank=True, null=True)),
                ('shot_made', models.BooleanField(blank=True, null=True)),
                ('shot_value', models.IntegerField(blank=True, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='games.game')),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_plays', to='players.player')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_plays', to='players.player')),
                ('player3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tertiary_plays', to='players.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plays', to='games.team')),
            ],
            options={
                'ordering': ['game', 'period', 'event_num'],
                'unique_together': {('game', 'event_num')},
            },
        ),
    ]
