# Generated by Django 6.0.4 on 2026-04-18 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_id_alter_team_id'),
        ('players', '0002_alter_player_id'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbyplay',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.CharField(blank=True, max_length=10, null=True)),
                ('pts', models.IntegerField(blank=True, null=True)),
                ('reb', models.IntegerField(blank=True, null=True)),
                ('ast', models.IntegerField(blank=True, null=True)),
                ('stl', models.IntegerField(blank=True, null=True)),
                ('blk', models.IntegerField(blank=True, null=True)),
                ('turnover', models.IntegerField(blank=True, null=True)),
                ('fgm', models.IntegerField(blank=True, null=True)),
                ('fga', models.IntegerField(blank=True, null=True)),
                ('fg_pct', models.FloatField(blank=True, null=True)),
                ('fg3m', models.IntegerField(blank=True, null=True)),
                ('fg3a', models.IntegerField(blank=True, null=True)),
                ('fg3_pct', models.FloatField(blank=True, null=True)),
                ('ftm', models.IntegerField(blank=True, null=True)),
                ('fta', models.IntegerField(blank=True, null=True)),
                ('ft_pct', models.FloatField(blank=True, null=True)),
                ('oreb', models.IntegerField(blank=True, null=True)),
                ('dreb', models.IntegerField(blank=True, null=True)),
                ('pf', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='games.team')),
            ],
            options={
                'unique_together': {('game', 'player')},
            },
        ),
    ]
