# Generated by Django 6.0.4 on 2026-04-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_postseason'),
        ('players', '0004_alter_player_nba_player_id'),
        ('stats', '0002_alter_playbyplay_id_playerstat'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='playerstat',
            index=models.Index(fields=['player'], name='stats_playe_player__30da8b_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstat',
            index=models.Index(fields=['team'], name='stats_playe_team_id_c53ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstat',
            index=models.Index(fields=['game'], name='stats_playe_game_id_c4f95a_idx'),
        ),
    ]
