# Generated by Django 6.0.4 on 2026-04-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_playerstat_stats_playe_player__30da8b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGameLog',
            fields=[
                ('playerstat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=10)),
                ('game_date', models.DateField()),
                ('home_team_id', models.IntegerField()),
                ('away_team_id', models.IntegerField()),
                ('home_score', models.IntegerField(null=True)),
                ('away_score', models.IntegerField(null=True)),
                ('minutes', models.CharField(max_length=10, null=True)),
                ('pts', models.IntegerField(null=True)),
                ('reb', models.IntegerField(null=True)),
                ('ast', models.IntegerField(null=True)),
                ('stl', models.IntegerField(null=True)),
                ('blk', models.IntegerField(null=True)),
                ('turnover', models.IntegerField(null=True)),
                ('fgm', models.IntegerField(null=True)),
                ('fga', models.IntegerField(null=True)),
                ('fg_pct', models.FloatField(null=True)),
                ('fg3m', models.IntegerField(null=True)),
                ('fg3a', models.IntegerField(null=True)),
                ('fg3_pct', models.FloatField(null=True)),
                ('ftm', models.IntegerField(null=True)),
                ('fta', models.IntegerField(null=True)),
                ('ft_pct', models.FloatField(null=True)),
                ('oreb', models.IntegerField(null=True)),
                ('dreb', models.IntegerField(null=True)),
                ('pf', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'player_game_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('gp', models.IntegerField()),
                ('ppg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('rpg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('apg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('spg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('bpg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('topg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fg_pct', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('fg3_pct', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('ft_pct', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('total_pts', models.IntegerField()),
                ('total_tov', models.IntegerField()),
                ('total_reb', models.IntegerField()),
                ('total_ast', models.IntegerField()),
            ],
            options={
                'db_table': 'player_season_stats',
                'managed': False,
            },
        ),
    ]
