# Generated by Django 6.0.4 on 2026-04-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_team_conference'),
        ('stats', '0004_playergamelog_playerseasonstats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playbyplay',
            options={'ordering': ['game', 'order']},
        ),
        migrations.RenameField(
            model_name='playbyplay',
            old_name='loc_x',
            new_name='coordinate_x',
        ),
        migrations.RenameField(
            model_name='playbyplay',
            old_name='loc_y',
            new_name='coordinate_y',
        ),
        migrations.RenameField(
            model_name='playbyplay',
            old_name='event_num',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='playbyplay',
            old_name='shot_value',
            new_name='score_value',
        ),
        migrations.AlterUniqueTogether(
            name='playbyplay',
            unique_together={('game', 'order')},
        ),
        migrations.AddField(
            model_name='playbyplay',
            name='scoring_play',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playbyplay',
            name='wallclock',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playbyplay',
            name='clock',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='playbyplay',
            name='event_type',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='playbyplay',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='playbyplay',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='playbyplay',
            name='player3',
        ),
        migrations.RemoveField(
            model_name='playbyplay',
            name='shot_distance',
        ),
        migrations.RemoveField(
            model_name='playbyplay',
            name='shot_made',
        ),
    ]
