# Generated by Django 6.0.4 on 2026-04-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_alter_playbyplay_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbyplay',
            name='participants',
            field=models.JSONField(default=list),
        ),
    ]
