# Generated by Django 6.0.4 on 2026-04-27 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_game_datetime_game_status'),
        ('stats', '0006_playbyplay_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_type', models.CharField(choices=[('BACK_AND_FORTH', 'Back and Forth'), ('RUN', 'Run'), ('BLOWOUT', 'Blowout'), ('TIGHT', 'Tight')], max_length=20)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('start_order', models.IntegerField()),
                ('end_order', models.IntegerField()),
                ('start_period', models.IntegerField()),
                ('end_period', models.IntegerField()),
                ('start_clock', models.CharField(max_length=20)),
                ('end_clock', models.CharField(max_length=20)),
                ('home_score_start', models.IntegerField()),
                ('away_score_start', models.IntegerField()),
                ('home_score_end', models.IntegerField()),
                ('away_score_end', models.IntegerField()),
                ('differential_start', models.IntegerField()),
                ('differential_end', models.IntegerField()),
                ('differential_max', models.IntegerField()),
                ('lead_change_count', models.IntegerField(default=0)),
                ('run_ratio', models.FloatField(blank=True, null=True)),
                ('dominant_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dominant_segments', to='games.team')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='games.game')),
            ],
            options={
                'ordering': ['game', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='GameKeyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TIE', 'Tie'), ('LEAD_CHANGE', 'Lead Change'), ('BLOWOUT_START', 'Blowout Start')], max_length=20)),
                ('play_order', models.IntegerField()),
                ('period', models.IntegerField()),
                ('clock', models.CharField(max_length=20)),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('differential', models.IntegerField()),
                ('benefiting_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_events', to='games.team')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_events', to='games.game')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_events', to='stats.gamesegment')),
            ],
            options={
                'ordering': ['game', 'play_order'],
            },
        ),
        migrations.AddIndex(
            model_name='gamesegment',
            index=models.Index(fields=['game', 'sequence'], name='stats_games_game_id_87dad6_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesegment',
            index=models.Index(fields=['game', 'segment_type'], name='stats_games_game_id_b62b1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gamesegment',
            unique_together={('game', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='gamekeyevent',
            index=models.Index(fields=['game', 'event_type'], name='stats_gamek_game_id_471733_idx'),
        ),
        migrations.AddIndex(
            model_name='gamekeyevent',
            index=models.Index(fields=['game', 'play_order'], name='stats_gamek_game_id_e6592b_idx'),
        ),
    ]
