# Generated by Django 6.0.4 on 2026-04-19 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0004_team_conference'),
        ('players', '0004_alter_player_nba_player_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(default='free', max_length=20)),
                ('favorite_players', models.ManyToManyField(blank=True, related_name='favorited_by', to='players.player')),
                ('favorite_teams', models.ManyToManyField(blank=True, related_name='favorited_by', to='games.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
