# Generated by Django 6.0.4 on 2026-04-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_id_alter_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='postseason',
            field=models.BooleanField(default=False),
        ),
    ]
