# Generated by Django 6.0.4 on 2026-04-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_postseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='conference',
            field=models.CharField(blank=True, choices=[('East', 'Eastern'), ('West', 'Western')], max_length=4, null=True),
        ),
    ]
