# Generated by Django 6.0.4 on 2026-04-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_team_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
