# Generated by Django 4.2.16 on 2026-04-17 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nba_player_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, choices=[('G', 'Guard'), ('F', 'Forward'), ('C', 'Center'), ('G-F', 'Guard-Forward'), ('F-C', 'Forward-Center')], max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='games.team')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
