# Generated by Django 6.0.4 on 2026-04-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bdl_player_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
