# Generated by Django 6.0.4 on 2026-04-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_bdl_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nba_player_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
